import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
import SmoothScroll from "@/components/SmoothScroll";

export const metadata = {
  title: "DevDestroyed | Roast your GitHub Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SmoothScroll />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
